### ISSUE TITLE
How do I hide the menubar icon?

### ISSUE THREAD

**Issue by chdiza** [mattr-/slate#7] opened 2014-12-22 17:05 UTC
I see that the ability to hide the menubar icon was just added, but I can't find any instructions on how to do this in my .slate file.

I tried `config menuBarIconHidden true`, but then Slate complains that that's an unrecognized config key.

**Comment by mattr-** [comment] 2015-01-14 15:42
Strange. I'll give this a try over the few days. I've been pretty swamped with other stuff lately.

**Comment by mattr-** [comment] 2015-01-18 17:05
My test build of Slate worked just fine when it came to hiding the menu bar. I'm going to assume this issue was some sort of environmental thing on you end and close it, seeing as how I couldn't reproduce the issue. Thanks!

**Closed by mattr-** 2015-01-18 17:05 UTC
